### ISSUE TITLE
alt attribute

### ISSUE THREAD

**Issue by gdedi001** [vickyhart/prj-rev-bwfs-tea-cozy#4]
Adding the `alt` attribute to image tags is a best practice. Make sure to use them at all times.
https://github.com/vickyhart/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/index.html#L37

https://www.w3schools.com/tags/att_img_alt.asp

**Comment by vickyhart** [comment]
You are right.  I completely forgot about them. Thank you
